Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.35.10"

  config.vagrant.plugins = "vagrant-hostsupdater"
  config.hostsupdater.aliases = ["hello.com", "python.com"]


  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y apache2
    cp -rf /vagrant/www/* /var/www
    cp -rf /vagrant/wsites/* /etc/apache2/wsites
    a2enmod ssl
    a2enmod cgid
    chmod +x ../../var/www/python/main.py
    a2ensite hello
    service apache2 restart
  SHELL
end
